package com.snapaie.android.domain.chat

/** Output-language catalog ported verbatim from the extension's languageMap. */
object Languages {
    val map: Map<String, String> = linkedMapOf(
        "en" to "English",
        "es" to "Spanish",
        "it" to "Italian",
        "de" to "German",
        "fr" to "French",
        "ru" to "Russian",
        "ar" to "Arabic",
        "zh" to "Chinese (Simplified, 简体中文)",
        "tr" to "Turkish",
        "bn" to "Bengali",
        "ur" to "Urdu",
        "hi" to "Hindi",
        "ja" to "Japanese",
        "ko" to "Korean",
        "pt" to "Portuguese",
        "nl" to "Dutch",
        "sv" to "Swedish",
        "da" to "Danish",
        "no" to "Norwegian",
        "fi" to "Finnish",
        "pl" to "Polish",
        "cs" to "Czech",
        "sk" to "Slovak",
        "hu" to "Hungarian",
        "ro" to "Romanian",
        "bg" to "Bulgarian",
        "hr" to "Croatian",
        "sl" to "Slovenian",
        "et" to "Estonian",
        "lv" to "Latvian",
        "lt" to "Lithuanian",
        "el" to "Greek",
        "he" to "Hebrew",
        "th" to "Thai",
        "vi" to "Vietnamese",
        "id" to "Indonesian",
        "ms" to "Malay",
        "tl" to "Tagalog",
        "uk" to "Ukrainian",
        "be" to "Belarusian",
        "ka" to "Georgian",
        "hy" to "Armenian",
        "az" to "Azerbaijani",
        "kk" to "Kazakh",
        "ky" to "Kyrgyz",
        "uz" to "Uzbek",
        "tg" to "Tajik",
        "mn" to "Mongolian",
    )

    fun nameFor(code: String): String = map[code.trim().lowercase()] ?: "English"
}
